server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exceldb
    username: postgres
    password: 1234qwer$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: secretkey123
  expirationMs: 86400000
